- name: Backup server.conf 
  hosts: all
  become: true
  become_user: splunk

  tasks:
    - name: Backup server.conf on all servers to server.conf.bak.ansible
      hosts: all
      copy:
        src: /opt/splunk/etc/system/local/server.conf
        dest: /opt/splunk/etc/system/local/server.conf.bak.ansible
        remote_src: yes
        owner: splunk
        group: splunk
        backup: yes
        force: no # don't overwrite the backup if it exists


- name: Backup web.conf on Splunk Web enabled servers
  hosts: splunk_web
  become: true
  become_user: splunk

  tasks:
    - name: Copy web.conf to web.conf.bak.ansible
      copy:
        src: /opt/splunk/etc/system/local/web.conf
        dest: /opt/splunk/etc/system/local/web.conf.bak.ansible
        remote_src: yes
        owner: splunk
        group: splunk
        backup: yes
        force: no # don't overwrite the backup if it exists
