- name: Configure web.conf on Splunk Web enabled servers where web.conf exists
  hosts: splunk_web
  become: true
  become_user: splunk
  tasks: 

    # Check if web.conf exists, if not skip the next tasks

    # Comment out #privKeyPath

    - name: Configure privKeyPath if it exists in web.conf
      lineinfile: 
        path: /opt/splunk/etc/system/local/web.conf
        regexp: '^privKeyPath.*'
        line: 'privKeyPath = $SPLUNK_HOME/etc/auth/new_cert/splunk-srv1.web.key'

    - name: Remove previous instances of serverCert (if any)
      lineinfile:
        path: /opt/splunk/etc/system/local/web.conf
        regexp: '^serverCert.*'
        state: absent

    - name: Configure caCertPath (deprecated) as serverCert if it exists in web.conf
      lineinfile:
        path: /opt/splunk/etc/system/local/web.conf
        regexp: '^caCertPath.*'
        line: 'caCertPath = $SPLUNK_HOME/etc/auth/new_cert/{{ inventory_hostname }}_web.pem'
    

