
- name: replace settings line
  hosts: index,index1,index2,index3,index4
  become: true
  become_user: splunk
  tasks:

    # replace line
    - name: replace line
      lineinfile:
        path: /opt/splunk/etc/system/local/web.conf
        regexp: '.*settings.*'
        line: '[settings]'

