- name: Restore server.conf prior to new cert updates
  hosts: all
  become: true
  become_user: splunk

  tasks:
    - name: Restore server.conf from server.conf.bak.01172019 backup
      copy:
        src: /opt/splunk/etc/system/local/server.conf.bak.01172019
        dest: /opt/splunk/etc/system/local/server.conf
        remote_src: yes
        owner: splunk
        group: splunk
 

- name: Restore web.conf on Splunk Web enabled servers
  hosts: splunk_web
  become: true
  become_user: splunk

  tasks:
    - name: Restore web.conf from web.conf.bak.01172019
      copy:
        src: /opt/splunk/etc/system/local/web.conf.bak.01172019
        dest: /opt/splunk/etc/system/local/web.conf
        remote_src: yes
        owner: splunk
        group: splunk
      ignore_errors: yes


- name: Remove uploaded certs
  hosts: all
  become: true
  become_user: splunk
  
  tasks:
    - name: Delete new certs
      shell: /bin/rm -rf /opt/splunk/etc/auth/new_cert/*
