- name: Backup server.conf 
  hosts: all
  become: true
  become_user: splunk

  tasks:
    - name: Copy server.conf to server.conf.bak.01172019
      copy:
        src: /opt/splunk/etc/system/local/server.conf
        dest: /opt/splunk/etc/system/local/server.conf.bak.01172019
        remote_src: yes
        owner: splunk
        group: splunk
        backup: yes
        force: no # don't overwrite the backup if it exists


- name: Backup web.conf on Splunk Web enabled servers
  hosts: itio*dpm01,cm,hf,adhoc,es
  become: true
  become_user: splunk

  tasks:
    - name: Copy web.conf to web.conf.bak.01172019
      copy:
        src: /opt/splunk/etc/system/local/web.conf
        dest: /opt/splunk/etc/system/local/web.conf.bak.01172019
        remote_src: yes
        owner: splunk
        group: splunk
        backup: yes
        force: no # don't overwrite the backup if it exists
- name: Upload new certs from controller to all remote hosts
  hosts: all
  become: true
  become_user: splunk
  
  tasks:

    - name: Upload each host's specific public cert to /opt/splunk/etc/auth/new_cert/
      copy:
        src: /tmp/certs/{{inventory_hostname}}/
        dest: /opt/splunk/etc/auth/new_cert/
        owner: splunk
        group: splunk

#    - name: Convert splunkd key to RSA format and secure it (Note you must clear the new_cert directory first using rollback.yaml)
#      command: openssl rsa -in splunk-srv1.key -out splunk-srv1.key -passin pass:051rT_5plUNk && chmod 400 splunk-srv1.key
#      args:
#        chdir: /opt/splunk/etc/auth/new_cert/
#        creates:  /opt/splunk/etc/auth/new_cert/splunk-srv1.key
#      no_log: true # don't want password in the logs

#    - name: Convert splunkweb key to RSA format and secure it
#      shell: openssl rsa -in splunk-srv1.web.key -out splunk-srv1.web.key && chmod 400 splunk-srv1.web.key
#      args:
#        chdir: /opt/splunk/etc/auth/new_cert/  
#        creates: /opt/splunk/etc/auth/new_cert/splunk-srv1.web.key

#    - name: Cat splunkweb to splunkd key
#      shell: rm -f splunk-srv1.key && cat splunk-srv1.web.key > splunk-srv1.key
#      args:
#        chdir: /opt/splunk/etc/auth/new_cert/

    - name: Concatenate splunkd certs into Splunk format (Note you must clear the new_cert directory first using rollback.yaml)
      shell: cat certnew.cer splunk-srv1.key rootchain.pem > {{ inventory_hostname }}.pem 
      args:
        chdir: /opt/splunk/etc/auth/new_cert/
        #creates: /opt/splunk/etc/auth/new_cert/{{ inventory_hostname}}.pem
   
    - name: Concatenate Splunk Web certs into Splunk format
      shell: cat certnew.cer rootchain.pem > {{ inventory_hostname }}_web.pem 
      args:
        chdir: /opt/splunk/etc/auth/new_cert/
        #creates: /opt/splunk/etc/auth/new_cert/{{ inventory_hostname }}_web.pem
    

- name: Configure server.conf 
  hosts: all
  become: true
  become_user: splunk
  tags: conf

  tasks:

# Delete old ones
    - name: remove any existing sslPassword or sslKeysfilePassword
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        regexp: '^sslPassword.*'
        state: absent
      no_log: true # we don't want passwords in the logs
    
    
    - name: remove existing serverCert if it exists
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        regexp: '^serverCert.*'
        state: absent

    - name: remove existing caCertFile
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        regexp: '^caCertFile.*'
        state: absent

    - name: remove existing caPath
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        regexp: '^caPath.*'
        state: absent

    - name: remove deprecated sslKeysFile
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        regexp: '^sslKeysfile.*'
        state: absent

    - name: remove sslKeysfilePassword
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        regexp: '^sslKeysfilePassword.*'
        state: absent

    - name: remove password from replication_port-ssl stanza
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        regexp: '^password.*'
        state: absent

# Add new configs    
    - name: Add new caCertFile
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        line: 'caCertFile = rootchain.pem'
        insertafter: '\[sslConfig\]'

    - name: Add new caPath
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        line: 'caPath = $SPLUNK_HOME/etc/auth/new_cert'
        insertafter: '\[sslConfig\]'

    - name: add requireClientCert = false
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        insertafter: '\[sslConfig\]'
        line: 'requireClientCert = false'
    
    - name: add enablesplunkdssl
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        insertafter: '\[sslConfig\]'
        line: 'enableSplunkdSSL = true'

    - name: add sslKeysfile 
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        insertafter: '\[sslConfig\]'
        line: 'sslKeysfile = {{inventory_hostname}}.pem'

    - name: add sslKeysfilePassword
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        insertafter: '\[sslConfig\]'
        line: 'sslKeysfilePassword = yourpassword
      no_log: true # no passwords in the logs

# NOTE: DO NOT SET sslPassword if sslKeysfilePassword is set for the sslConfig stanza in server.conf! It will be automatically set by splunk upon restaring splunkd in local/server.conf
#    - name: add sslPassword
#      lineinfile:
#        path: /opt/splunk/etc/system/local/server.conf
#        insertafter: '\[sslConfig\]'
#        line: 'sslPassword = yourpassword
#      no_log: true # no passwords in the logs

    - name: set sslPassword for the replication_port-ssl stanza if it exists
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        insertafter: '^\[replication_port-ssl.*'
        line: 'password = yourpasword
      #no_log: true # no passwords in the logs

    - name: set rootCA for the replication_port-ssl stanza if it exists
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        insertafter: '^\[replication_port-ssl.*'
        line: 'rootCA = $SPLUNK_HOME/etc/auth/new_cert/rootchain.pem'

    - name: set serverCert for the replicaiton_port-ssl stanza if it exists
      lineinfile:
        path: /opt/splunk/etc/system/local/server.conf
        insertafter: '^\[replication_port-ssl.*'
        line: 'serverCert = $SPLUNK_HOME/etc/auth/new_cert/{{ inventory_hostname }}.pem'


- name: Configure web.conf on Splunk Web enabled servers where web.conf exists
  hosts: itio*dpm01,cm,hf,adhoc,es
  become: true
  become_user: splunk
  tasks: 

    # Check if web.conf exists, if not skip the next tasks

    # Comment out #privKeyPath

    - name: Configure privKeyPath if it exists in web.conf
      lineinfile: 
        path: /opt/splunk/etc/system/local/web.conf
        regexp: '^privKeyPath.*'
        line: 'privKeyPath = $SPLUNK_HOME/etc/auth/new_cert/splunk-srv1.web.key'

    - name: Remove previous instances of serverCert (if any)
      lineinfile:
        path: /opt/splunk/etc/system/local/web.conf
        regexp: '^serverCert.*'
        state: absent

    - name: Configure caCertPath (deprecated) as serverCert if it exists in web.conf
      lineinfile:
        path: /opt/splunk/etc/system/local/web.conf
        regexp: '^caCertPath.*'
        line: 'caCertPath = $SPLUNK_HOME/etc/auth/new_cert/{{ inventory_hostname }}_web.pem'
    

- name: Configure web.conf on Indexers or where web.conf doesn't exist 
  hosts: itio*idx*, itio*dpr*
  become: true
  become_user: splunk
  tasks:

    # Confirm web.conf doesn't exist 
    # Create [settings] stanza and ensure web.conf is created

    # Comment out caCertPath
    - name: Add [settings] stanza to web.conf
      lineinfile:
        path: /opt/splunk/etc/system/local/web.conf
        line: '[settings]'
        state: present
        create: yes

    - name: Add privKeyPath to web.conf after [settings] stanza
      lineinfile:
        path: /opt/splunk/etc/system/local/web.conf
        line: 'privKeyPath = $SPLUNK_HOME/etc/auth/new_cert/splunk-srv1.web.key'
        insertafter: '\[settings\]'

    - name: Add serverCert to web.conf after privKeyPath 
      lineinfile:
        path: /opt/splunk/etc/system/local/web.conf
        line: 'caCertPath = $SPLUNK_HOME/etc/auth/new_cert/{{ inventory_hostname }}_web.pem'
        insertafter: '\[settings\]'

# Add sslVersions
    - name: Add sslVersions to web.conf after serverCert
      lineinfile:
        path: /opt/splunk/etc/system/local/web.conf
        line: 'sslVersions = tls, -tls1.0'
        insertafter: 'serverCert'

#  hosts: es deploy cm adhoc hf
  
